---
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files:
         - vars.yml
  tasks:
 
    - when: ansible_os_family == "RedHat"
      set_fact: package_name=httpd

    - set_fact: package_name=apache2
      when: ansible_os_family == "Debian"

    - name: Install httpd package
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"

    - name: Install apache2 package
      yum: name=apache2 state=latest
      when: ansible_os_family == "Debian"
    
    - name: Check apache service
      service: name={{ package_name }} state=started
