--- #PLAYBOOK FOR PACKAGE ADDING AND UPDATE
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files: 
         - files/vars_remote_redhat.yml
  tasks:
  - name: Update the package on Redhat Based System
    when: ansible_os_family == "RedHat"
    yum: name={{ item }} state=latest
    async: 40
    poll: 10
    with_items:
    - "{{ var_package }}"
