--- #PLAYBOOK FOR PACKAGE REMOVAL
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files: 
         - var.yml
  tasks:
  - name: Remove Package on Redhat Based System
    when: ansible_os_family == "RedHat"
    yum: name={{ item }} state=absent
    async: 40
    poll: 10
    with_items:
    - newrelic-repo
