--- #PLAYBOOK FOR USER ADD
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files: 
         - files/vars_remote_redhat.yml
  tasks:
  - name: testing
    user: name=test1 state=present
  - name: what is your name
    user: name=test state=absent
